all:
  .array:
    weekdays:
      7:  Sunday
      1:  Monday
      2:  Tuesday
      3:  Wednesday
      4:  Thursday
      5:  Friday
      6:  Saturday
    durations:
      1:  week(s)
      2:  month(s)
      3:  year(s)
    nt_books:
      1:  Matthew
      2:  Mark
      3:  Luke
      4:  John
      5:  Acts
      6:  Romans
      7:  1 Corinthians
      8:  2 Corinthians
      9:  Galations
      10: Ephesians
      11: Phillipians
      12: Colossians
      13: 1 Thessalonians
      14: 2 Thessalonians
      15: 1 Timothy
      16: 2 Timothy
      17: Titus
      18: Philemon
      19: Hebrews
      20: James
      21: 1 Peter
      22: 2 Peter
      23: 1 John
      24: 2 John
      25: 3 John
      26: Jude
      27: Revelation